run_name: ddpm_cifar10
seed: 42
data_dir: ./data  # Directory for downloading CIFAR-10 automatically
image_size: 32  # CIFAR-10 original size; or set to 128 if resizing images
batch_size: 16  # Adjust based on available GPU memory; 16 is a common choice
num_workers: 4  # Set based on your system's CPU cores
num_classes: 10  # CIFAR-10 has 10 classes
num_epochs: 50
learning_rate: 1e-4
weight_decay: 1e-4

# Diffusion process parameters
num_train_timesteps: 1000
num_inference_steps: 200
beta_start: 0.0001
beta_end: 0.02
beta_schedule: 'linear'

variance_type: fixed_small
prediction_type: epsilon

# U-Net configuration
unet_in_size: 32  # Change to 128 if resizing images
unet_in_ch: 3
unet_ch: 128
unet_num_res_blocks: 2
unet_ch_mult: [1, 2, 4]  # Adjust if necessary
unet_attn: [1]  # Attention layers, simplified for smaller images
unet_dropout: 0.0
